# Generated by Django 5.2.15 on 2026-06-18 05:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'graph_project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('effort_hours', models.FloatField(default=0.0)),
                ('position_x', models.FloatField(default=0.0)),
                ('position_y', models.FloatField(default=0.0)),
                ('earliest_start', models.FloatField(default=0.0)),
                ('earliest_finish', models.FloatField(default=0.0)),
                ('latest_start', models.FloatField(default=0.0)),
                ('latest_finish', models.FloatField(default=0.0)),
                ('total_slack', models.FloatField(default=0.0)),
                ('is_critical', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='graph.project')),
            ],
            options={
                'db_table': 'graph_node',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='graph.node')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='graph.node')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='graph.project')),
            ],
            options={
                'db_table': 'graph_edge',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(fields=('project', 'label'), name='uq_node_project_label'),
        ),
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.UniqueConstraint(fields=('source', 'target'), name='uq_edge_source_target'),
        ),
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.CheckConstraint(condition=models.Q(('source', models.F('target')), _negated=True), name='ck_edge_no_self_loop'),
        ),
    ]
